"""Typed ECL calculation result contracts."""

from .grouping import (
    ECLGroupingPolicy,
    ECLMeasurementRoute,
    GroupingMember,
    HomogeneityMetric,
    HomogeneityReport,
    HomogeneousGroupDefinition,
    build_homogeneous_group_id,
    load_ecl_grouping_policy,
    route_ecl_measurement,
    validate_homogeneous_group,
)
from .models import ECLResult, ScenarioECL
from .poci import (
    POCICashFlow,
    POCIClassification,
    POCIMeasurement,
    POCIScenarioCashFlows,
    POCIScenarioMeasurement,
    POCIScenarioResult,
    classify_poci,
    credit_adjusted_eir,
    measure_poci_change,
    measure_poci_scenarios,
)
from .scenario_engine import (
    BaselineRiskPeriod,
    ProbabilityWeightedScenarioECL,
    ScenarioIntegral,
    ScenarioRiskPeriod,
    calculate_probability_weighted_scenario_ecl,
)
from .sensitivity import (
    ScenarioSensitivityPolicy,
    ScenarioSensitivityReport,
    SensitivityResult,
    TrajectoryShock,
    WeightSensitivityCase,
    load_scenario_sensitivity_policy,
    run_scenario_sensitivities,
)
from .stage1 import (
    Stage1ContractInput,
    Stage1ECLResult,
    Stage1RiskPeriod,
    calculate_stage1_ecl,
)
from .stage2 import (
    Stage2CalculationMode,
    Stage2ContractInput,
    Stage2ECLResult,
    Stage2RiskPeriod,
    calculate_stage2_ecl,
)

__all__ = [
    "ECLResult",
    "ECLGroupingPolicy",
    "ECLMeasurementRoute",
    "GroupingMember",
    "HomogeneityMetric",
    "HomogeneityReport",
    "HomogeneousGroupDefinition",
    "BaselineRiskPeriod",
    "POCICashFlow",
    "POCIClassification",
    "POCIMeasurement",
    "POCIScenarioCashFlows",
    "POCIScenarioMeasurement",
    "POCIScenarioResult",
    "ProbabilityWeightedScenarioECL",
    "ScenarioECL",
    "ScenarioIntegral",
    "ScenarioRiskPeriod",
    "ScenarioSensitivityPolicy",
    "ScenarioSensitivityReport",
    "SensitivityResult",
    "Stage1ContractInput",
    "Stage1ECLResult",
    "Stage1RiskPeriod",
    "Stage2CalculationMode",
    "Stage2ContractInput",
    "Stage2ECLResult",
    "Stage2RiskPeriod",
    "TrajectoryShock",
    "WeightSensitivityCase",
    "calculate_probability_weighted_scenario_ecl",
    "calculate_stage1_ecl",
    "calculate_stage2_ecl",
    "build_homogeneous_group_id",
    "classify_poci",
    "credit_adjusted_eir",
    "measure_poci_change",
    "measure_poci_scenarios",
    "load_scenario_sensitivity_policy",
    "load_ecl_grouping_policy",
    "run_scenario_sensitivities",
    "route_ecl_measurement",
    "validate_homogeneous_group",
]
