"""Versioned Document 3040 generation and pre-validation."""

from .contract import (
    FIELD_CATALOG,
    Accounting4966,
    AdditionalInformation,
    Aggregation,
    Client,
    ConnectedIpoc,
    ConnectedIpocGroup,
    Doc3040Input,
    FieldSpec,
    Guarantee,
    Header,
    MaturityValue,
    Operation,
    RecognizedLoss,
    Requirement,
    SicorInformation,
    SourcedValue,
    SourceRef,
    StageAllocation,
    assert_catalog_covers_models,
    catalog_fields_for,
    iter_sourced_values,
    sourced,
)

__all__ = [
    "FIELD_CATALOG",
    "Accounting4966",
    "AdditionalInformation",
    "Aggregation",
    "Client",
    "ConnectedIpoc",
    "ConnectedIpocGroup",
    "Doc3040Input",
    "FieldSpec",
    "Guarantee",
    "Header",
    "MaturityValue",
    "Operation",
    "RecognizedLoss",
    "Requirement",
    "SicorInformation",
    "SourceRef",
    "SourcedValue",
    "StageAllocation",
    "assert_catalog_covers_models",
    "catalog_fields_for",
    "iter_sourced_values",
    "sourced",
]
